# Derived from pinned GrandOrgue CMake source list; GPL-2.0-or-later.
set(GO_CORE_SOURCES
  ${GO_SOURCE}/src/core/archive/GOArchive.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveCreator.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveFile.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveIndex.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveEntryFile.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveManager.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveReader.cpp
  ${GO_SOURCE}/src/core/archive/GOArchiveWriter.cpp
  ${GO_SOURCE}/src/core/config/GOConfigEnum.cpp
  ${GO_SOURCE}/src/core/config/GOConfigFileReader.cpp
  ${GO_SOURCE}/src/core/config/GOConfigFileWriter.cpp
  ${GO_SOURCE}/src/core/config/GOConfigReader.cpp
  ${GO_SOURCE}/src/core/config/GOConfigReaderDB.cpp
  ${GO_SOURCE}/src/core/config/GOConfigWriter.cpp
  ${GO_SOURCE}/src/core/contrib/sha1.cpp
  ${GO_SOURCE}/src/core/files/GOInvalidFile.cpp
  ${GO_SOURCE}/src/core/files/GOStandardFile.cpp
  ${GO_SOURCE}/src/core/files/GOStdFileName.cpp
  ${GO_SOURCE}/src/core/settings/GOSetting.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingBool.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingDirectory.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingEnum.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingFile.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingFloat.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingStore.cpp
  ${GO_SOURCE}/src/core/settings/GOSettingString.cpp
  ${GO_SOURCE}/src/core/threading/GOCondition.cpp
  ${GO_SOURCE}/src/core/threading/GOMutex.cpp
  ${GO_SOURCE}/src/core/threading/GOMutexLocker.cpp
  ${GO_SOURCE}/src/core/threading/GOThread.cpp
  ${GO_SOURCE}/src/core/threading/threading_impl.cpp
  ${GO_SOURCE}/src/core/temperaments/GOTemperament.cpp
  ${GO_SOURCE}/src/core/temperaments/GOTemperamentCent.cpp
  ${GO_SOURCE}/src/core/temperaments/GOTemperamentList.cpp
  ${GO_SOURCE}/src/core/temperaments/GOTemperamentUser.cpp
  ${GO_SOURCE}/src/core/GOCompress.cpp
  ${GO_SOURCE}/src/core/GOCrashHandler.cpp
  ${GO_SOURCE}/src/core/GOHash.cpp
  ${GO_SOURCE}/src/core/GOLogicalColour.cpp
  ${GO_SOURCE}/src/core/GOMemoryPool.cpp
  ${GO_SOURCE}/src/core/GONameMap.cpp
  ${GO_SOURCE}/src/core/GOOrgan.cpp
  ${GO_SOURCE}/src/core/GOOrganList.cpp
  ${GO_SOURCE}/src/core/GOSampleStatistic.cpp
  ${GO_SOURCE}/src/core/GOStdPath.cpp
  ${GO_SOURCE}/src/core/GOTimer.cpp
  ${GO_SOURCE}/src/core/GOWave.cpp
  ${GO_SOURCE}/src/core/GOWavPack.cpp
  ${GO_SOURCE}/src/core/GOWavPackWriter.cpp
  ${GO_SOURCE}/src/core/go_path.cpp
)
