# Derived from pinned GrandOrgue CMake source list; GPL-2.0-or-later.
set(GO_ENGINE_SOURCES
  ${GO_SOURCE}/src/grandorgue/combinations/control/GOCombinationButtonSet.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/control/GOCombinationControllerProxy.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/control/GODivisionalButtonControl.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/control/GOGeneralButtonControl.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/model/GOCombination.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/model/GOCombinationDefinition.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/model/GODivisionalCombination.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/model/GOGeneralCombination.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/GODivisionalSetter.cpp
  ${GO_SOURCE}/src/grandorgue/combinations/GOSetter.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOAudioDeviceConfig.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOAudioDeviceNode.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOConfig.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOConfigMidiObject.cpp
  ${GO_SOURCE}/src/grandorgue/config/GODeviceNamePattern.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOMidiDeviceConfig.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOMidiDeviceConfigList.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOPortsConfig.cpp
  ${GO_SOURCE}/src/grandorgue/config/GOPortFactory.cpp
  ${GO_SOURCE}/src/grandorgue/config/GORegisteredOrgan.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOButtonControl.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOCallbackButtonControl.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOElementCreator.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOEventDistributor.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOLabelControl.cpp
  ${GO_SOURCE}/src/grandorgue/control/GOPistonControl.cpp
  ${GO_SOURCE}/src/grandorgue/loader/GOFileStore.cpp
  ${GO_SOURCE}/src/grandorgue/loader/GOLoaderFilename.cpp
  ${GO_SOURCE}/src/grandorgue/loader/GOLoadThread.cpp
  ${GO_SOURCE}/src/grandorgue/loader/GOLoadWorker.cpp
  ${GO_SOURCE}/src/grandorgue/loader/GOOrganReader.cpp
  ${GO_SOURCE}/src/grandorgue/loader/cache/GOCache.cpp
  ${GO_SOURCE}/src/grandorgue/loader/cache/GOCacheCleaner.cpp
  ${GO_SOURCE}/src/grandorgue/loader/cache/GOCacheWriter.cpp
  ${GO_SOURCE}/src/grandorgue/midi/elements/GOMidiReceiver.cpp
  ${GO_SOURCE}/src/grandorgue/midi/elements/GOMidiShortcutReceiver.cpp
  ${GO_SOURCE}/src/grandorgue/midi/elements/GOMidiSendProxy.cpp
  ${GO_SOURCE}/src/grandorgue/midi/elements/GOMidiSender.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiEvent.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiEventPattern.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiReceiverEventPattern.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiSenderEventPattern.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiShortcutPattern.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GOMidiWxEvent.cpp
  ${GO_SOURCE}/src/grandorgue/midi/events/GORodgers.cpp
  ${GO_SOURCE}/src/grandorgue/midi/files/GOMidiFileReader.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiObject.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiObjectContext.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiObjectWithDivision.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiObjectWithShortcut.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiPlayingObject.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiReceivingSendingObject.cpp
  ${GO_SOURCE}/src/grandorgue/midi/objects/GOMidiSendingObject.cpp
  ${GO_SOURCE}/src/grandorgue/midi/ports/GOMidiInPort.cpp
  ${GO_SOURCE}/src/grandorgue/midi/ports/GOMidiOutPort.cpp
  ${GO_SOURCE}/src/grandorgue/midi/ports/GOMidiPort.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiInputMerger.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiListener.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiOutputMerger.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiPlayer.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiPlayerContent.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiRecorder.cpp
  ${GO_SOURCE}/src/grandorgue/midi/GOMidiSystem.cpp
  ${GO_SOURCE}/src/grandorgue/model/pipe-config/GOPipeConfig.cpp
  ${GO_SOURCE}/src/grandorgue/model/pipe-config/GOPipeConfigNode.cpp
  ${GO_SOURCE}/src/grandorgue/model/pipe-config/GOPipeConfigTreeNode.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOCacheObject.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOCoupler.cpp
  ${GO_SOURCE}/src/grandorgue/model/GODivisionalCoupler.cpp
  ${GO_SOURCE}/src/grandorgue/model/GODrawstop.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOEnclosure.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOEventHandlerList.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOManual.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOOrganModel.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOPipe.cpp
  ${GO_SOURCE}/src/grandorgue/model/GORank.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOReferencePipe.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOReferencingObject.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOSoundingPipe.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOStop.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOSwitch.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOTremulant.cpp
  ${GO_SOURCE}/src/grandorgue/model/GOWindchest.cpp
  ${GO_SOURCE}/src/grandorgue/modification/GOModificationProxy.cpp
  ${GO_SOURCE}/src/grandorgue/scheduler/GOScheduler.cpp
  ${GO_SOURCE}/src/grandorgue/scheduler/GOSchedulerThread.cpp
  ${GO_SOURCE}/src/grandorgue/sound/interfaces/GOSoundCallbackConnector.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundAudioSection.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundFader.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundReleaseAlignTable.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundResample.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundSamplerPlayer.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundSamplerPool.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundStream.cpp
  ${GO_SOURCE}/src/grandorgue/sound/playing/GOSoundToneBalanceFilter.cpp
  ${GO_SOURCE}/src/grandorgue/sound/ports/GOSoundJackPort.cpp
  ${GO_SOURCE}/src/grandorgue/sound/ports/GOSoundPort.cpp
  ${GO_SOURCE}/src/grandorgue/sound/processing/GOSoundProcessingChain.cpp
  ${GO_SOURCE}/src/grandorgue/sound/processing/GOSoundProcessingChainState.cpp
  ${GO_SOURCE}/src/grandorgue/sound/providers/GOSoundProvider.cpp
  ${GO_SOURCE}/src/grandorgue/sound/providers/GOSoundProviderSynthedTrem.cpp
  ${GO_SOURCE}/src/grandorgue/sound/providers/GOSoundProviderWave.cpp
  ${GO_SOURCE}/src/grandorgue/sound/reverb/GOSoundReverb.cpp
  ${GO_SOURCE}/src/grandorgue/sound/reverb/GOSoundReverbEngine.cpp
  ${GO_SOURCE}/src/grandorgue/sound/reverb/GOSoundReverbPartition.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundGroupTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundOutputTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundRecorderTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundReleaseTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundTaskBase.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundTouchTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundTremulantTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/tasks/GOSoundWindchestTask.cpp
  ${GO_SOURCE}/src/grandorgue/sound/GOSoundDevInfo.cpp
  ${GO_SOURCE}/src/grandorgue/sound/GOSoundOnePoleFilter.cpp
  ${GO_SOURCE}/src/grandorgue/sound/GOSoundOrganEngine.cpp
  ${GO_SOURCE}/src/grandorgue/sound/GOSoundSystem.cpp
  ${GO_SOURCE}/src/grandorgue/yaml/GOSaveableToYaml.cpp
  ${GO_SOURCE}/src/grandorgue/yaml/GOYamlModel.cpp
  ${GO_SOURCE}/src/grandorgue/yaml/go-wx-yaml.cpp
  ${GO_SOURCE}/src/grandorgue/GOAudioRecorder.cpp
  ${GO_SOURCE}/src/grandorgue/GOKeyConvert.cpp
  ${GO_SOURCE}/src/grandorgue/GOMetronome.cpp
  ${GO_SOURCE}/src/grandorgue/GOOrganController.cpp
  ${GO_SOURCE}/src/grandorgue/GOVirtualCouplerController.cpp
  ${GO_SOURCE}/src/grandorgue/gui/size/GOSizeKeeper.cpp
  ${GO_SOURCE}/src/grandorgue/gui/dialogs/common/GODialogSizeSet.cpp
)
